/**
* Generated by go-doudou v2.1.5.
* You can edit it as your need.
 */
package service

import (
	"context"

	"github.com/VINDA-98/doudou-test/config"
	"github.com/VINDA-98/doudou-test/dto"
	"github.com/brianvoe/gofakeit/v6"
)

var _ DoudouTest = (*DoudouTestImpl)(nil)

type DoudouTestImpl struct {
	conf *config.Config
}

func (receiver *DoudouTestImpl) PostUser(ctx context.Context, user dto.GddUser) (data int32, err error) {
	var _result struct {
		Data int32
	}
	_ = gofakeit.Struct(&_result)
	return _result.Data, nil
}
func (receiver *DoudouTestImpl) GetUser_Id(ctx context.Context, id int32) (data dto.GddUser, err error) {
	var _result struct {
		Data dto.GddUser
	}
	_ = gofakeit.Struct(&_result)
	return _result.Data, nil
}
func (receiver *DoudouTestImpl) PutUser(ctx context.Context, user dto.GddUser) (re error) {
	var _result struct {
	}
	_ = gofakeit.Struct(&_result)
	return nil
}
func (receiver *DoudouTestImpl) DeleteUser_Id(ctx context.Context, id int32) (re error) {
	var _result struct {
	}
	_ = gofakeit.Struct(&_result)
	return nil
}
func (receiver *DoudouTestImpl) GetUsers(ctx context.Context, parameter dto.Parameter) (data dto.Page, err error) {
	var _result struct {
		Data dto.Page
	}
	_ = gofakeit.Struct(&_result)
	return _result.Data, nil
}

func NewDoudouTest(conf *config.Config) *DoudouTestImpl {
	return &DoudouTestImpl{
		conf: conf,
	}
}
