/**
* Generated by go-doudou v2.1.5.
* You can edit it as your need.
 */
package main

import (
	service "github.com/VINDA-98/doudou-test"
	"github.com/VINDA-98/doudou-test/config"
	"github.com/VINDA-98/doudou-test/transport/httpsrv"
	"github.com/unionj-cloud/go-doudou/v2/framework/rest"
)

func main() {
	conf := config.LoadFromEnv()
	svc := service.NewDoudouTest(conf)
	handler := httpsrv.NewDoudouTestHandler(svc)
	srv := rest.NewRestServer()
	srv.AddRoute(httpsrv.Routes(handler)...)
	srv.Run()
}
